- name: Updating ca-certificates package
  become: yes
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: latest
    update_cache: yes

- name: Downloading gpg keyring
  become: yes
  ansible.builtin.get_url:
    url: "{{ storpool_apt_keyring_url }}"
    dest: /usr/share/keyrings/storpool-keyring.gpg
    mode: 0644

- name: Adding StorPool APT repositories
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb deb-src [signed-by=/usr/share/keyrings/storpool-keyring.gpg] https://repo.storpool.com/public/{{ item.url_path }}/ubuntu/ {{ ansible_distribution_release }} main"
    filename: "{{ item.filename }}"
  loop: "{{ storpool_repositories }}"
