- name: Updating APT cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when:
    - ansible_os_family == 'Debian'

- name: Updating ca-certificates
  become: yes
  ansible.builtin.package:
    name:
      - ca-certificates
    state: latest

- name: Adding storpool repository
  include_tasks: "add-repo-{{ ansible_os_family | lower }}.yml"

- name: Installing StorPool Python packages
  become: yes
  ansible.builtin.package:
    name:
      - sp-python2
      - sp-python2-modules
      - sp-python3
      - sp-python3-modules
    state: present
